export type Rarity = 'Common' | 'Uncommon' | 'Rare' | 'Ultra-Rare' | 'Legendary'
export type PetVariant = 'Normal' | 'Fly' | 'Ride' | 'Fly Ride' | 'Neon' | 'Mega Neon'

export interface Pet {
  id: string
  name: string
  rarity: Rarity
  emoji: string
  bgColor: string
  glowColor: string
  basePrice: number
  description: string
  limited?: boolean
  hot?: boolean
  featured?: boolean
  stock?: number
}

export const RARITY_COLORS: Record<Rarity, string> = {
  Common: '#6b7280',
  Uncommon: '#22c55e',
  Rare: '#3b82f6',
  'Ultra-Rare': '#a855f7',
  Legendary: '#f59e0b',
}

export const RARITY_GRADIENTS: Record<Rarity, string> = {
  Common: 'from-gray-800 to-gray-700',
  Uncommon: 'from-green-950 to-green-900',
  Rare: 'from-blue-950 to-blue-900',
  'Ultra-Rare': 'from-purple-950 to-purple-900',
  Legendary: 'from-amber-950 to-orange-900',
}

export const VARIANT_MULTIPLIERS: Record<PetVariant, number> = {
  Normal: 1,
  Fly: 1.6,
  Ride: 1.6,
  'Fly Ride': 2.8,
  Neon: 4.5,
  'Mega Neon': 18,
}

export const VARIANT_LABELS: Record<PetVariant, string> = {
  Normal: '🐾 Normal',
  Fly: '✈️ Fly',
  Ride: '🎮 Ride',
  'Fly Ride': '⚡ Fly Ride',
  Neon: '✨ Neon',
  'Mega Neon': '🌈 Mega Neon',
}

export function getPetPrice(pet: Pet, variant: PetVariant): number {
  return Math.round(pet.basePrice * VARIANT_MULTIPLIERS[variant] * 100) / 100
}

export function getPetById(id: string): Pet | undefined {
  return pets.find((p) => p.id === id)
}

export const pets: Pet[] = [
  // ─── Legendary ───────────────────────────────────────────────────────────
  {
    id: 'shadow-dragon',
    name: 'Shadow Dragon',
    rarity: 'Legendary',
    emoji: '🐉',
    bgColor: '#3b0764',
    glowColor: '#a855f7',
    basePrice: 149.99,
    description: "The rarest and most feared dragon. Born from pure shadow magic — a true collector's crown jewel.",
    limited: true,
    hot: true,
    featured: true,
    stock: 2,
  },
  {
    id: 'bat-dragon',
    name: 'Bat Dragon',
    rarity: 'Legendary',
    emoji: '🦇',
    bgColor: '#431407',
    glowColor: '#f97316',
    basePrice: 129.99,
    description: 'Born from Halloween magic, this legendary dragon spreads its wings across the night sky.',
    limited: true,
    hot: true,
    featured: true,
    stock: 3,
  },
  {
    id: 'frost-dragon',
    name: 'Frost Dragon',
    rarity: 'Legendary',
    emoji: '🐉',
    bgColor: '#0c4a6e',
    glowColor: '#38bdf8',
    basePrice: 119.99,
    description: 'Forged in ice and snow — the Frost Dragon breathes blizzards and commands winter itself.',
    limited: true,
    featured: true,
    stock: 4,
  },
  {
    id: 'giraffe',
    name: 'Giraffe',
    rarity: 'Legendary',
    emoji: '🦒',
    bgColor: '#451a03',
    glowColor: '#f59e0b',
    basePrice: 99.99,
    description: 'The tallest and most majestic pet. Incredibly rare and instantly recognizable.',
    limited: true,
    hot: true,
    stock: 5,
  },
  {
    id: 'parrot',
    name: 'Parrot',
    rarity: 'Legendary',
    emoji: '🦜',
    bgColor: '#052e16',
    glowColor: '#22c55e',
    basePrice: 89.99,
    description: 'Vivid and colorful, the Parrot is a beloved legendary companion from the Jungle Egg.',
    limited: true,
    stock: 7,
  },
  {
    id: 'kangaroo',
    name: 'Kangaroo',
    rarity: 'Legendary',
    emoji: '🦘',
    bgColor: '#431407',
    glowColor: '#ea580c',
    basePrice: 79.99,
    description: 'Bouncing with energy, this legendary marsupial carries joy wherever it hops.',
    stock: 9,
  },
  {
    id: 'dragon',
    name: 'Dragon',
    rarity: 'Legendary',
    emoji: '🐉',
    bgColor: '#450a0a',
    glowColor: '#ef4444',
    basePrice: 69.99,
    description: 'The classic Adopt Me dragon — a timeless symbol of power and prestige.',
    featured: true,
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    rarity: 'Legendary',
    emoji: '🦄',
    bgColor: '#500724',
    glowColor: '#ec4899',
    basePrice: 59.99,
    description: 'Magical and pure, the Unicorn leaves a rainbow trail wherever it roams.',
    featured: true,
  },
  {
    id: 'evil-unicorn',
    name: 'Evil Unicorn',
    rarity: 'Legendary',
    emoji: '🦄',
    bgColor: '#2e1065',
    glowColor: '#7c3aed',
    basePrice: 59.99,
    description: 'The dark twin of the Unicorn, wielding menacing purple magic.',
    limited: true,
    stock: 6,
  },
  {
    id: 'griffin',
    name: 'Griffin',
    rarity: 'Legendary',
    emoji: '🦅',
    bgColor: '#422006',
    glowColor: '#d97706',
    basePrice: 54.99,
    description: 'Half eagle, half lion — the Griffin commands respect in every neighborhood.',
  },
  {
    id: 'crow',
    name: 'Crow',
    rarity: 'Legendary',
    emoji: '🐦',
    bgColor: '#0f172a',
    glowColor: '#94a3b8',
    basePrice: 49.99,
    description: 'Mysterious and wise, the Crow is a legendary bird wrapped in myth.',
  },
  {
    id: 'owl',
    name: 'Owl',
    rarity: 'Legendary',
    emoji: '🦉',
    bgColor: '#292524',
    glowColor: '#a78bfa',
    basePrice: 54.99,
    description: 'The wise Owl watches over adventures with ancient magical sight.',
  },
  {
    id: 'kitsune',
    name: 'Kitsune',
    rarity: 'Legendary',
    emoji: '🦊',
    bgColor: '#431407',
    glowColor: '#fb923c',
    basePrice: 64.99,
    description: 'A mystical nine-tailed fox with ancient spirit magic flowing through its fur.',
    hot: true,
  },
  {
    id: 'golden-dragon',
    name: 'Golden Dragon',
    rarity: 'Legendary',
    emoji: '🐉',
    bgColor: '#422006',
    glowColor: '#fbbf24',
    basePrice: 74.99,
    description: 'Radiant and gilded — this special dragon is an absolute showstopper.',
  },
  {
    id: 'diamond-dragon',
    name: 'Diamond Dragon',
    rarity: 'Legendary',
    emoji: '🐉',
    bgColor: '#0c4a6e',
    glowColor: '#67e8f9',
    basePrice: 89.99,
    description: 'Shimmering with crystal clarity, the Diamond Dragon is pure luxury.',
    hot: true,
  },
  {
    id: 'golden-unicorn',
    name: 'Golden Unicorn',
    rarity: 'Legendary',
    emoji: '🦄',
    bgColor: '#422006',
    glowColor: '#fbbf24',
    basePrice: 64.99,
    description: 'Gilded and gleaming, the Golden Unicorn is the ultimate flex.',
  },
  {
    id: 'diamond-unicorn',
    name: 'Diamond Unicorn',
    rarity: 'Legendary',
    emoji: '🦄',
    bgColor: '#0c4a6e',
    glowColor: '#a5f3fc',
    basePrice: 79.99,
    description: 'Crystalline and flawless, the Diamond Unicorn sparkles in the sunlight.',
  },
  {
    id: 'cerberus',
    name: 'Cerberus',
    rarity: 'Legendary',
    emoji: '🐕',
    bgColor: '#450a0a',
    glowColor: '#f87171',
    basePrice: 69.99,
    description: 'The three-headed guardian of the underworld, now your fiercely loyal companion.',
  },

  // ─── Ultra-Rare ───────────────────────────────────────────────────────────
  {
    id: 'dodo',
    name: 'Dodo',
    rarity: 'Ultra-Rare',
    emoji: '🦤',
    bgColor: '#2e1065',
    glowColor: '#a855f7',
    basePrice: 29.99,
    description: 'Extinct in real life but alive in Adopt Me! A rare and precious find.',
    hot: true,
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    rarity: 'Ultra-Rare',
    emoji: '🦩',
    bgColor: '#500724',
    glowColor: '#f472b6',
    basePrice: 24.99,
    description: 'Standing tall and pink, the Flamingo is the queen of the lagoon.',
  },
  {
    id: 'elephant',
    name: 'Elephant',
    rarity: 'Ultra-Rare',
    emoji: '🐘',
    bgColor: '#1e293b',
    glowColor: '#94a3b8',
    basePrice: 22.99,
    description: 'Gentle and wise, this ultra-rare pachyderm never forgets a friend.',
  },
  {
    id: 'panda',
    name: 'Panda',
    rarity: 'Ultra-Rare',
    emoji: '🐼',
    bgColor: '#0f172a',
    glowColor: '#cbd5e1',
    basePrice: 19.99,
    description: 'Black, white, and adorable all over — the Panda is a crowd favorite.',
  },
  {
    id: 'red-panda',
    name: 'Red Panda',
    rarity: 'Ultra-Rare',
    emoji: '🦊',
    bgColor: '#422006',
    glowColor: '#f97316',
    basePrice: 24.99,
    description: 'This fiery little furball is rarer than its name suggests.',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    rarity: 'Ultra-Rare',
    emoji: '🦚',
    bgColor: '#042f2e',
    glowColor: '#2dd4bf',
    basePrice: 22.99,
    description: 'Spreading its magnificent tail, the Peacock is pure elegance personified.',
  },
  {
    id: 'turtle',
    name: 'Turtle',
    rarity: 'Ultra-Rare',
    emoji: '🐢',
    bgColor: '#052e16',
    glowColor: '#4ade80',
    basePrice: 19.99,
    description: 'Slow and steady, the Turtle outlasts them all. A timeless companion.',
  },
  {
    id: 'rhino',
    name: 'Rhino',
    rarity: 'Ultra-Rare',
    emoji: '🦏',
    bgColor: '#1c1917',
    glowColor: '#a8a29e',
    basePrice: 17.99,
    description: 'Tough and powerful, the Rhino charges through any adventure.',
  },
  {
    id: 'platypus',
    name: 'Platypus',
    rarity: 'Ultra-Rare',
    emoji: '🦦',
    bgColor: '#1c0a00',
    glowColor: '#d97706',
    basePrice: 22.99,
    description: "Nature's greatest mystery makes for Adopt Me's quirkiest companion.",
  },
  {
    id: 'snow-owl',
    name: 'Snow Owl',
    rarity: 'Ultra-Rare',
    emoji: '🦉',
    bgColor: '#0c1445',
    glowColor: '#bfdbfe',
    basePrice: 26.99,
    description: 'Pure white and ethereal, the Snow Owl glides silently through winter skies.',
    limited: true,
  },
  {
    id: 'hyena',
    name: 'Hyena',
    rarity: 'Ultra-Rare',
    emoji: '🐺',
    bgColor: '#292207',
    glowColor: '#ca8a04',
    basePrice: 17.99,
    description: 'Always laughing, the Hyena brings chaotic joy wherever it roams.',
  },

  // ─── Rare ─────────────────────────────────────────────────────────────────
  {
    id: 'bunny',
    name: 'Bunny',
    rarity: 'Rare',
    emoji: '🐰',
    bgColor: '#172554',
    glowColor: '#60a5fa',
    basePrice: 9.99,
    description: 'Fluffy and fast — the Bunny is a beloved rare companion from the Easter Egg.',
    limited: true,
  },
  {
    id: 'wolf',
    name: 'Wolf',
    rarity: 'Rare',
    emoji: '🐺',
    bgColor: '#1e293b',
    glowColor: '#64748b',
    basePrice: 8.99,
    description: 'Running with the pack or lone wolf — this rare canine is always loyal.',
  },
  {
    id: 'penguin',
    name: 'Penguin',
    rarity: 'Rare',
    emoji: '🐧',
    bgColor: '#0f172a',
    glowColor: '#93c5fd',
    basePrice: 9.99,
    description: 'Waddling with dignity, the rare Penguin is winter\'s cutest friend.',
  },
  {
    id: 'reindeer',
    name: 'Reindeer',
    rarity: 'Rare',
    emoji: '🦌',
    bgColor: '#1c0a00',
    glowColor: '#dc2626',
    basePrice: 9.99,
    description: 'Prancing through snow, this rare holiday companion never goes out of season.',
    limited: true,
  },
  {
    id: 'narwhal',
    name: 'Narwhal',
    rarity: 'Rare',
    emoji: '🦄',
    bgColor: '#1e1b4b',
    glowColor: '#818cf8',
    basePrice: 11.99,
    description: 'The unicorn of the sea! This rare aquatic wonder is truly special.',
  },
  {
    id: 'swan',
    name: 'Swan',
    rarity: 'Rare',
    emoji: '🦢',
    bgColor: '#1e1e2e',
    glowColor: '#e2e8f0',
    basePrice: 8.99,
    description: 'Gliding gracefully, the rare Swan is elegance in feathered form.',
  },
  {
    id: 'pig',
    name: 'Pig',
    rarity: 'Rare',
    emoji: '🐷',
    bgColor: '#500724',
    glowColor: '#f9a8d4',
    basePrice: 7.99,
    description: 'Curly-tailed and cheerful — this rare piggy brings happiness everywhere.',
  },
  {
    id: 'duck',
    name: 'Duck',
    rarity: 'Rare',
    emoji: '🦆',
    bgColor: '#292207',
    glowColor: '#fde047',
    basePrice: 7.99,
    description: 'Quack! This rare feathered friend waddles straight into your heart.',
  },

  // ─── Uncommon ─────────────────────────────────────────────────────────────
  {
    id: 'horse',
    name: 'Horse',
    rarity: 'Uncommon',
    emoji: '🐴',
    bgColor: '#1a2e05',
    glowColor: '#4ade80',
    basePrice: 4.99,
    description: 'Gallop through neighborhoods with this beloved uncommon companion.',
  },
  {
    id: 'chocolate-lab',
    name: 'Chocolate Lab',
    rarity: 'Uncommon',
    emoji: '🐕',
    bgColor: '#1c0a00',
    glowColor: '#92400e',
    basePrice: 3.99,
    description: "Man's best friend in a chocolatey uncommon package.",
  },
  {
    id: 'bee',
    name: 'Bee',
    rarity: 'Uncommon',
    emoji: '🐝',
    bgColor: '#292207',
    glowColor: '#fbbf24',
    basePrice: 4.99,
    description: 'Buzzing with energy, this uncommon bee pollinates your adventures.',
  },
  {
    id: 'poodle',
    name: 'Poodle',
    rarity: 'Uncommon',
    emoji: '🐩',
    bgColor: '#500724',
    glowColor: '#f472b6',
    basePrice: 3.99,
    description: 'Fancy and fabulous — this uncommon poodle struts with pure style.',
  },

  // ─── Common ───────────────────────────────────────────────────────────────
  {
    id: 'dog',
    name: 'Dog',
    rarity: 'Common',
    emoji: '🐕',
    bgColor: '#1e293b',
    glowColor: '#94a3b8',
    basePrice: 1.99,
    description: 'The classic starter pet! Every Adopt Me journey begins with this loyal friend.',
  },
  {
    id: 'cat',
    name: 'Cat',
    rarity: 'Common',
    emoji: '🐱',
    bgColor: '#1e293b',
    glowColor: '#94a3b8',
    basePrice: 1.99,
    description: 'Independent and cute — the Cat is the perfect companion for any player.',
  },
  {
    id: 'chicken',
    name: 'Chicken',
    rarity: 'Common',
    emoji: '🐔',
    bgColor: '#292207',
    glowColor: '#fbbf24',
    basePrice: 0.99,
    description: 'Clucking with joy, the Chicken is the most wholesome common pet.',
  },
  {
    id: 'otter',
    name: 'Otter',
    rarity: 'Common',
    emoji: '🦦',
    bgColor: '#1c0a00',
    glowColor: '#92400e',
    basePrice: 1.49,
    description: 'Playful and precious — the Otter holds your heart like a pebble.',
  },
  {
    id: 'buffalo',
    name: 'Buffalo',
    rarity: 'Common',
    emoji: '🐃',
    bgColor: '#1c1917',
    glowColor: '#78716c',
    basePrice: 1.49,
    description: 'Strong and sturdy, the Buffalo is a dependable common companion.',
  },
]
